[package]
name = "teo-parser"
version = "0.0.58"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.5"
pest_derive = "2.7.5"
teo-teon = "0.0.58"
colored = "2.0.4"
pathdiff = "0.2.1"
once_cell = "1.18.0"
maplit = "1.0.2"
array_tool = "1.0.3"
itertools = "0.11.0"
snailquote = "0.3.1"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
path-clean = "1.0.1"
educe = "0.4.23"
indexmap = { version = "2.1.0", features = ["serde"] }